export const RouterPath = {
    HOME: '/',
    FLIGHTS : 'Flights',
    FLIGHTSDETAILS : '/FlightsDetails/:id',
    HOTELS : '/Hotels',
    HOTELDETAILS : '/HotelDetails/:id',
    PACKAGES : '/Packages',
    PROFILE : '/Profile',
    SIGNIN : '/SignIn',
    SIGNUP : '/SignUp',
    FORGETPASSWORD : '/ForgetPassword',
    VERIFYCODE: '/VerifyCode',
    RESETPASSWORD : '/ResetPassword',
    FORMONE : '/FormOne',
    FORMTWO : '/FormTwo',
    ORDERSEAT : '/OrderSeat',
    ERROR404 : '*',
}